##installs necessary packages
- name: python.yml - install python2, pip, and boto
  package:
      state: present # required. Whether to install (C(present)), or remove (C(absent)) a package. Other states depend on the underlying package module, i.e C(latest).
      name: "{{ item }}" # required. Package name, or package specifier with version, like C(name-1.0).,Be aware that packages are not always named the same and this module will not 'translate' them per distro.
      use: auto # not required. The required package manager module to use (yum, apt, etc). The default 'auto' will use existing facts or try to autodetect it.,You should only use this field if the automatic selection is not working for some reason.
  
  with_items:
     - python
     - python-pip
     - python-boto

- name: python.yml - Copy AWS Access ID and Secret Key into .boto file
  file:
      path: ~/.boto
      state: present