---
#General vars
target: localhost
#vars for build_iam



# vars file for init_ec2_hosts
public_ip_yes_no: yes
ssh_key_name: "{{ init_aws_ec2_ssh_key_name }}"
image_id:  "{{ init_aws_image_id }}"
vpc_subnet_id: subnet-94ddc6fc
instance_type: "{{ init_aws_instance_type }}"
wait: yes
group: default
region: "{{ init_aws_region_id }}"
instance_count: "{{ init_aws_instance_count }}"

# Networking 
test_ports: [8000]

...